version: "3.4"

services:
  database:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass
      POSTGRES_DB: my_db
    ports:
      - 35434:5432
