version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.14.2
      - image: circleci/postgres:12
        name: database
        environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin_pass
          POSTGRES_DB: my_db
    working_directory: ~/go-migrations
    steps:
      - checkout
      - run: make install
      - run: DB_HOST=database DB_PORT=5432 make test-no-bootstrap
